### PR TITLE
feat: Create dropna.md documentation.

### PR DESCRIPTION
**Pull request by DayneSorvisto**
Added some documentation for dropna based on references. Example compiled locally:

image

### CODE REVIEW

**Comment by kdpsingh** [comment]
Appreciate the PR! Thank you for contributing.

Our Contributor instructions are a bit out of date (which we need to fix). Because we are using `Literate.jl` to compile documentation, this actually needs to get converted to a `.jl` file and placed in the folder with all the other `.jl` files, with the `.yml` file updated to include this `.jl` file in the table of contents.

If you want to give it a shot, feel free to move it there and convert it into an actual `.jl` file that runs in Julia. If you're not sure what to do, I'm happy to have a colleague help out.

One other thing is that for the docs, the example should have more explanation and a tutorial style than what is there in the `References`. I'm happy to add some of that at the end, but the docs shouldn't just be a restating of the `References`.

**Comment by DayneSorvisto** [comment]
@kdpsingh thanks for the feedback. This is a great project and I'd be interested in contributing to documentation. Let me see if I can get a bit more familiar with Literate and the code base over next few days (I'll push a few more commits here to give it a shot) and then I may have some more questions or need some help I'll update here if I make progress.

**Comment by DayneSorvisto** [comment]
Hi @kdpsingh  I added a basic tutorial and organize into a tutorial (summary, table of contents, examples, basic usage, advanced examples and additional help) for drop_na.

I wasn't sure how the tables are generated or if the formatting is correct (I created a generate markdown script in Julia but may look different locally).

**Comment by kdpsingh** [comment]
Hi @DayneSorvisto I will look through what you had prepared and will return to this in the future.

**Pull request closed without merging**
