### PR TITLE
Implementing functions proposed in #48

### PR DESCRIPTION
**Pull request by alonsoC1s**
Implements `as_float, as_integer, as_string` and adds tests for the added functionality as mentioned in #48 .

### CODE REVIEW

**Comment by kdpsingh** [comment]
Thank you for this! I'm planning to move the tests to docstrings and am happy to take it from here.

**Comment by alonsoC1s** [comment]
Excelent! I can still help getting this ready to merge by changing the test, checking why the build fails, etc.

**Comment by lazarusA** [comment]
maybe try to avoid using `catch` and `try` and use something more like a `ismissing` conditional instead.

**Comment by alonsoC1s** [comment]
I'm sorry, I'm struggling to see why we should avoid `try` blocks. Is there any particular reason?

**Comment by kdpsingh** [comment]
I think there are 2 philosophies of error handling: 1. look before you leap (anticipate errors and handle proactively) and 2. easier to ask for forgiveness (try/catch).

Both are described here: https://scls.gitbooks.io/ljthw/content/_chapters/11-ex8.html

Culturally, I think the first approach is considered more "correct" by many in the Julia than the second (which is commonly used in R/Python).

There may potentially be other advantages to the first (in terms of compiler-friendliness/efficiency/speed) but I'm quite used to try/catch and don't see a major issue with it as you've used it here (and it may be unavoidable without anticipating lots of potential contingencies).

**Comment by lazarusA** [comment]
those functions already have `::Union{AbstractFloat, Missing}`, so you already have only 2 options. Honestly, I don't see the need for try and catch if this is already settled from the start.

**Comment by kdpsingh** [comment]
I will try to remove and see if the behavior changes. My worry is that `parse(Float, "hello")` will generate an error instead of returning a missing value unless we wrap in try/catch.

I'm not sure if specifying the return type will fix that behavior.

Will try and see how it goes (am still new to Julia so truly not sure how it will behave).

**Pull request merged**
